create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  department text,
  employee_code text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.employees
  add column if not exists is_active boolean not null default true;

alter table if exists public.employees
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'employees'
      and c.conname = 'employees_employee_code_key'
  ) then
    alter table public.employees
      add constraint employees_employee_code_key unique (employee_code);
  end if;
end;
$$;

drop trigger if exists set_employees_updated_at on public.employees;
create trigger set_employees_updated_at
before update on public.employees
for each row execute function public.touch_updated_at();
