create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  department text,
  employee_code text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.employees
  add column if not exists is_active boolean not null default true;

alter table if exists public.employees
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_employees_updated_at on public.employees;
create trigger set_employees_updated_at
before update on public.employees
for each row execute function public.touch_updated_at();
