create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  department text,
  employee_code text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_employee_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_employee_code text := upper(
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'emp_id'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'employee_code'), '')
    )
  );
  v_name text := nullif(
    trim(
      coalesce(
        new.raw_user_meta_data ->> 'name',
        new.raw_user_meta_data ->> 'full_name',
        split_part(coalesce(new.email, ''), '@', 1)
      )
    ),
    ''
  );
  v_department text := nullif(trim(new.raw_user_meta_data ->> 'department'), '');
begin
  if v_employee_code is null or v_employee_code = '' then
    raise exception 'Employee ID is required to create an account';
  end if;

  insert into public.employees (name, email, department, employee_code, is_active)
  values (
    coalesce(v_name, 'New User'),
    nullif(lower(coalesce(new.email, '')), ''),
    coalesce(v_department, 'General'),
    v_employee_code,
    true
  )
  on conflict (employee_code) do update
  set
    name = excluded.name,
    email = excluded.email,
    department = excluded.department,
    is_active = true,
    updated_at = now();

  return new;
end;
$$;

alter table if exists public.employees
  add column if not exists is_active boolean not null default true;

alter table if exists public.employees
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'employees'
      and c.conname = 'employees_employee_code_key'
  ) then
    alter table public.employees
      add constraint employees_employee_code_key unique (employee_code);
  end if;
end;
$$;

insert into public.employees (name, email, department, employee_code, is_active)
select
  coalesce(
    nullif(
      trim(
        coalesce(
          u.raw_user_meta_data ->> 'name',
          u.raw_user_meta_data ->> 'full_name',
          split_part(coalesce(u.email, ''), '@', 1)
        )
      ),
      ''
    ),
    'New User'
  ),
  nullif(lower(coalesce(u.email, '')), ''),
  coalesce(nullif(trim(u.raw_user_meta_data ->> 'department'), ''), 'General'),
  upper(
    coalesce(
      nullif(trim(u.raw_user_meta_data ->> 'emp_id'), ''),
      nullif(trim(u.raw_user_meta_data ->> 'employee_code'), '')
    )
  ),
  true
from auth.users u
where upper(
  coalesce(
    nullif(trim(u.raw_user_meta_data ->> 'emp_id'), ''),
    nullif(trim(u.raw_user_meta_data ->> 'employee_code'), '')
  )
) <> ''
on conflict (employee_code) do update
set
  name = excluded.name,
  email = excluded.email,
  department = excluded.department,
  is_active = true,
  updated_at = now();

drop trigger if exists set_employees_updated_at on public.employees;
create trigger set_employees_updated_at
before update on public.employees
for each row execute function public.touch_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_employee_profile();
