create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default '',
  location text not null default '',
  max_players integer not null default 4,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.games
  add column if not exists max_players integer not null default 4;

alter table if exists public.games
  add column if not exists active boolean not null default true;

alter table if exists public.games
  add column if not exists sort_order integer not null default 0;

alter table if exists public.games
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_games_updated_at on public.games;
create trigger set_games_updated_at
before update on public.games
for each row execute function public.touch_updated_at();

insert into public.games (name, icon, location, max_players, active, sort_order)
select v.name, v.icon, v.location, v.max_players, v.active, v.sort_order
from (
  values
    ('Carrom', 'CARROM', 'Recreation Room - 2nd Floor', 4, true, 1),
    ('Table Tennis', 'TT', 'Recreation Room - 2nd Floor', 2, true, 2),
    ('Chess', 'CHESS', 'Conference Room - 1st Floor', 2, true, 3)
) as v(name, icon, location, max_players, active, sort_order)
where not exists (
  select 1
  from public.games g
  where lower(g.name) = lower(v.name)
);
