create table if not exists public.slots (
  id bigint generated by default as identity primary key,
  label text not null,
  start_time time,
  end_time time,
  duration text not null default '30 min',
  game text not null default 'all',
  day text not null default 'all',
  max_players integer not null default 4,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.slots
  add column if not exists max_players integer not null default 4;

alter table if exists public.slots
  add column if not exists active boolean not null default true;

alter table if exists public.slots
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_slots_updated_at on public.slots;
create trigger set_slots_updated_at
before update on public.slots
for each row execute function public.touch_updated_at();

insert into public.slots (id, label, start_time, end_time, duration, game, day, max_players, active)
values
  (1, 'Slot 1', '11:00', '11:30', '30 min', 'all', 'all', 4, true),
  (2, 'Slot 2', '11:30', '12:00', '30 min', 'all', 'all', 4, true),
  (3, 'Slot 3', '12:00', '12:30', '30 min', 'all', 'all', 4, true),
  (4, 'Slot 4', '12:30', '13:00', '30 min', 'all', 'all', 4, true),
  (5, 'Slot 5', '13:00', '13:30', '30 min', 'all', 'all', 4, true),
  (6, 'Slot 6', '13:30', '14:00', '30 min', 'all', 'all', 4, true),
  (7, 'Slot 7', '14:00', '14:30', '30 min', 'all', 'all', 4, true),
  (8, 'Slot 8', '14:30', '15:00', '30 min', 'all', 'all', 4, true),
  (9, 'Slot 9', '15:00', '15:30', '30 min', 'all', 'all', 4, true),
  (10, 'Slot 10', '15:30', '16:00', '30 min', 'all', 'all', 4, true),
  (11, 'Slot 11', '16:00', '16:30', '30 min', 'all', 'all', 4, true),
  (12, 'Slot 12', '16:30', '17:00', '30 min', 'all', 'all', 4, true)
on conflict (id) do nothing;
