create table if not exists public.bans (
  id bigint generated by default as identity primary key,
  employee text not null,
  employee_id text not null references public.employees(employee_code) on update cascade on delete restrict,
  game text not null,
  from_date date not null default current_date,
  until_date date not null,
  reason text not null,
  created_by text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.bans
  add column if not exists created_by text;

alter table if exists public.bans
  add column if not exists active boolean not null default true;

alter table if exists public.bans
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_bans_updated_at on public.bans;
create trigger set_bans_updated_at
before update on public.bans
for each row execute function public.touch_updated_at();
