create table if not exists public.rules (
  id bigint generated by default as identity primary key,
  rule_description text not null,
  created_at date not null default current_date,
  created_by text not null default 'Admin',
  game text not null default 'General',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table if exists public.rules
  add column if not exists active boolean not null default true;

alter table if exists public.rules
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_rules_updated_at on public.rules;
create trigger set_rules_updated_at
before update on public.rules
for each row execute function public.touch_updated_at();

insert into public.rules (rule_description, created_at, created_by, game, active)
select v.rule_description, current_date, 'Admin', v.game, true
from (
  values
    ('Bookings are permitted for a maximum of one game per day.', 'General'),
    ('If a member fails to utilize their reserved time slot, the booking will be considered forfeited.', 'General'),
    ('Bookings can be entered or cancelled up to 15 minutes before the scheduled time. The member only enters their own name.', 'General'),
    ('Only one active booking per player per game per day. If a player fails to show up within 10 minutes of the booked time, the slot may be given to someone else. Players must maintain silence and avoid disturbing others. No use of mobile phones or loud conversations during the game.', 'General'),
    ('Each time slot has a fixed duration. Members must vacate at the end of their session to allow smooth transition for the next user.', 'General'),
    ('Members are expected to maintain cleanliness and follow game etiquette. Improper behavior or damage may result in suspension of booking privileges. Report any missing or damaged items to the manager.', 'General'),
    ('Please ask for carrom coins from Mr. Abhishek and hand them back at the end of your slot.', 'Carrom'),
    ('Do not move the carrom board from its location.', 'Carrom'),
    ('For any suggestions regarding usage or time slots, please contact Mr. Abhishek (+91-9289132909).', 'General'),
    ('If you are getting blocked every month for 3 consecutive months, you will be automatically blocked for the upcoming 3 months. If the blocked person has any questions, kindly direct them to Mr. Abhishek Mishra for any clarification.', 'General')
) as v(rule_description, game)
where not exists (
  select 1
  from public.rules r
  where r.rule_description = v.rule_description
    and r.game = v.game
);
