create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  day text not null,
  slot_id bigint not null references public.slots(id) on update cascade on delete restrict,
  player_name text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  employee_id text not null references public.employees(employee_code) on update cascade on delete restrict,
  game text not null,
  booked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.bookings
  add column if not exists employee_id text;

alter table if exists public.bookings
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_bookings_updated_at on public.bookings;
create trigger set_bookings_updated_at
before update on public.bookings
for each row execute function public.touch_updated_at();

drop trigger if exists validate_booking_trigger on public.bookings;
create trigger validate_booking_trigger
before insert or update on public.bookings
for each row execute function public.validate_booking_row();
