create table if not exists public.violations (
  id bigint generated by default as identity primary key,
  employee text not null,
  employee_id text,
  game text not null default 'General',
  rule text,
  reason text not null,
  status text not null default 'open',
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.violations
  add column if not exists employee_id text;

alter table if exists public.violations
  add column if not exists created_by text;

alter table if exists public.violations
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_violations_updated_at on public.violations;
create trigger set_violations_updated_at
before update on public.violations
for each row execute function public.touch_updated_at();
