-- Events table
-- Stores both upcoming and past company / outstation / celebration / tournament events.
-- Status is derived from the event date; `event_status` lets admins override
-- (e.g. mark a future event as "completed" once it wraps up, or push a past
-- event to "cancelled").

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  description text,
  event_type text not null default 'company',
  start_date date not null,
  end_date date,
  start_time time,
  end_time time,
  venue text,
  location text,
  organizer text,
  max_participants integer,
  banner_color text,
  icon text,
  created_by text,
  is_published boolean not null default true,
  event_status text not null default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (event_type in ('company', 'tournament', 'outstation', 'celebration')),
  check (event_status in ('scheduled', 'ongoing', 'completed', 'cancelled', 'postponed')),
  check (end_date is null or end_date >= start_date)
);

create index if not exists events_start_date_idx on public.events (start_date);
create index if not exists events_event_type_idx on public.events (event_type);
create index if not exists events_event_status_idx on public.events (event_status);

alter table if exists public.events
  add column if not exists description text;

alter table if exists public.events
  add column if not exists end_date date;

alter table if exists public.events
  add column if not exists start_time time;

alter table if exists public.events
  add column if not exists end_time time;

alter table if exists public.events
  add column if not exists venue text;

alter table if exists public.events
  add column if not exists location text;

alter table if exists public.events
  add column if not exists organizer text;

alter table if exists public.events
  add column if not exists max_participants integer;

alter table if exists public.events
  add column if not exists banner_color text;

alter table if exists public.events
  add column if not exists icon text;

alter table if exists public.events
  add column if not exists created_by text;

alter table if exists public.events
  add column if not exists is_published boolean not null default true;

alter table if exists public.events
  add column if not exists event_status text not null default 'scheduled';

alter table if exists public.events
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row execute function public.touch_updated_at();

-- Auto-stamp event_status from the date when it isn't manually set.
create or replace function public.events_sync_status()
returns trigger
language plpgsql
as $$
begin
  if new.event_status is null
     or new.event_status in ('scheduled', 'ongoing', 'completed')
  then
    if new.end_date is not null and new.end_date < current_date then
      new.event_status := 'completed';
    elsif new.start_date < current_date
          and (new.end_date is null or new.end_date >= current_date)
    then
      new.event_status := 'ongoing';
    elsif new.start_date >= current_date then
      new.event_status := 'scheduled';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists events_sync_status_trigger on public.events;
create trigger events_sync_status_trigger
before insert or update on public.events
for each row execute function public.events_sync_status();
