-- Tournaments table
-- A tournament is a structured competition for a single game.
-- Format drives the bracket (knockout, round-robin, league).
-- Status mirrors the lifecycle: registration -> live -> completed.

create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  game text not null,
  event_id bigint references public.events(id) on update cascade on delete set null,
  format text not null default 'knockout',
  start_date date not null,
  end_date date,
  registration_open boolean not null default true,
  max_participants integer not null default 8,
  status text not null default 'registration_open',
  champion_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  runner_up_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  third_place_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  prize_pool text,
  rules text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (format in ('knockout', 'round_robin', 'league', 'swiss')),
  check (status in ('draft', 'registration_open', 'live', 'completed', 'cancelled'))
);

create index if not exists tournaments_game_idx on public.tournaments (game);
create index if not exists tournaments_status_idx on public.tournaments (status);
create index if not exists tournaments_start_date_idx on public.tournaments (start_date);

alter table if exists public.tournaments
  add column if not exists description text;

alter table if exists public.tournaments
  add column if not exists event_id bigint references public.events(id) on update cascade on delete set null;

alter table if exists public.tournaments
  add column if not exists end_date date;

alter table if exists public.tournaments
  add column if not exists prize_pool text;

alter table if exists public.tournaments
  add column if not exists rules text;

alter table if exists public.tournaments
  add column if not exists created_by text;

alter table if exists public.tournaments
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_tournaments_updated_at on public.tournaments;
create trigger set_tournaments_updated_at
before update on public.tournaments
for each row execute function public.touch_updated_at();
