-- Tournament participants table
-- One row per (tournament, employee). Seed is the entry seeding used in the
-- bracket draw; matches_played / won / lost track the live progress.

create table if not exists public.tournament_participants (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on update cascade on delete cascade,
  employee_id text not null references public.employees(employee_code) on update cascade on delete restrict,
  seed integer,
  matches_played integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  points integer not null default 0,
  status text not null default 'registered',
  registered_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, employee_id),
  check (status in ('registered', 'active', 'semi_finalist', 'finalist', 'eliminated', 'withdrawn'))
);

alter table if exists public.tournament_participants
  drop constraint if exists tournament_participants_status_check;

alter table if exists public.tournament_participants
  add constraint tournament_participants_status_check
  check (status in ('registered', 'active', 'semi_finalist', 'finalist', 'eliminated', 'withdrawn'));

create index if not exists tournament_participants_tournament_idx on public.tournament_participants (tournament_id);
create index if not exists tournament_participants_employee_idx on public.tournament_participants (employee_id);

alter table if exists public.tournament_participants
  add column if not exists seed integer;

alter table if exists public.tournament_participants
  add column if not exists matches_played integer not null default 0;

alter table if exists public.tournament_participants
  add column if not exists wins integer not null default 0;

alter table if exists public.tournament_participants
  add column if not exists losses integer not null default 0;

alter table if exists public.tournament_participants
  add column if not exists points integer not null default 0;

alter table if exists public.tournament_participants
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_tournament_participants_updated_at on public.tournament_participants;
create trigger set_tournament_participants_updated_at
before update on public.tournament_participants
for each row execute function public.touch_updated_at();
