-- Tournament registration requests table
-- Keeps non-admin tournament signups separate from approved participants so
-- the existing participant flow stays untouched.

create table if not exists public.tournament_registration_requests (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on update cascade on delete cascade,
  employee_id text not null references public.employees(employee_code) on update cascade on delete restrict,
  status text not null default 'pending',
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, employee_id),
  check (status in ('pending'))
);

create index if not exists tournament_registration_requests_tournament_idx
  on public.tournament_registration_requests (tournament_id);

create index if not exists tournament_registration_requests_employee_idx
  on public.tournament_registration_requests (employee_id);

alter table if exists public.tournament_registration_requests
  add column if not exists status text not null default 'pending';

alter table if exists public.tournament_registration_requests
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_tournament_registration_requests_updated_at on public.tournament_registration_requests;
create trigger set_tournament_registration_requests_updated_at
before update on public.tournament_registration_requests
for each row execute function public.touch_updated_at();
