-- Tournament matches table
-- Each row is a single match inside a tournament bracket.
-- Round labels follow the standard: QF / SF / F / 3rd-place.
-- `next_match_winner_id` / `next_match_loser_id` are optional pointers used to
-- walk the bracket tree (winner of M1 advances to M5; loser of SF goes to 3rd
-- place match, etc).

create table if not exists public.tournament_matches (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on update cascade on delete cascade,
  match_code text not null,
  round text not null default 'QF',
  match_number integer not null default 1,
  player_a_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  player_b_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  score_a integer,
  score_b integer,
  winner_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  status text not null default 'scheduled',
  scheduled_at timestamptz,
  played_at timestamptz,
  duration_seconds integer,
  next_match_winner_id bigint references public.tournament_matches(id) on update cascade on delete set null,
  next_match_loser_id bigint references public.tournament_matches(id) on update cascade on delete set null,
  notes text,
  recorded_by_employee_id text references public.employees(employee_code) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tournament_id, match_code),
  check (btrim(round) <> ''),
  check (status in ('scheduled', 'in_progress', 'completed', 'draw', 'walkover', 'rescheduled', 'cancelled', 'disputed', 'no_show', 'bye', 'overdue', 'pending', 'live'))
);

create index if not exists tournament_matches_tournament_idx on public.tournament_matches (tournament_id);
create index if not exists tournament_matches_round_idx on public.tournament_matches (round);
create index if not exists tournament_matches_status_idx on public.tournament_matches (status);

alter table if exists public.tournament_matches
  add column if not exists score_a integer;

alter table if exists public.tournament_matches
  add column if not exists score_b integer;

alter table if exists public.tournament_matches
  add column if not exists winner_employee_id text references public.employees(employee_code) on update cascade on delete set null;

alter table if exists public.tournament_matches
  add column if not exists scheduled_at timestamptz;

alter table if exists public.tournament_matches
  add column if not exists played_at timestamptz;

alter table if exists public.tournament_matches
  add column if not exists duration_seconds integer;

alter table if exists public.tournament_matches
  add column if not exists next_match_winner_id bigint references public.tournament_matches(id) on update cascade on delete set null;

alter table if exists public.tournament_matches
  add column if not exists next_match_loser_id bigint references public.tournament_matches(id) on update cascade on delete set null;

alter table if exists public.tournament_matches
  add column if not exists notes text;

alter table if exists public.tournament_matches
  add column if not exists recorded_by_employee_id text references public.employees(employee_code) on update cascade on delete set null;

alter table if exists public.tournament_matches
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_tournament_matches_updated_at on public.tournament_matches;
create trigger set_tournament_matches_updated_at
before update on public.tournament_matches
for each row execute function public.touch_updated_at();
