-- Leaderboard table
-- Materialised all-time activity points per (employee, game).
-- Points are awarded based on the achievement rules:
--   tournament_win        = 20
--   tournament_runner_up  = 15
--   tournament_3rd        = 10
--   match_win             = 5
--   participation         = 2
--   rule_violation        = -5
--   no_show               = -3
--
-- The view `leaderboard_with_rank` (in 16_views.sql) ranks rows by points
-- so the UI can simply SELECT * FROM leaderboard_with_rank.

create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  employee_id text not null references public.employees(employee_code) on update cascade on delete cascade,
  game text not null default 'all',
  total_points integer not null default 0,
  tournament_wins integer not null default 0,
  tournament_seconds integer not null default 0,
  tournament_thirds integer not null default 0,
  match_wins integer not null default 0,
  match_losses integer not null default 0,
  draws integer not null default 0,
  participations integer not null default 0,
  rule_violations integer not null default 0,
  no_shows integer not null default 0,
  last_activity_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, game)
);

create index if not exists leaderboard_points_idx on public.leaderboard (total_points desc);
create index if not exists leaderboard_game_idx on public.leaderboard (game);

alter table if exists public.leaderboard
  add column if not exists tournament_wins integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists tournament_seconds integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists tournament_thirds integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists match_wins integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists match_losses integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists draws integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists participations integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists rule_violations integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists no_shows integer not null default 0;

alter table if exists public.leaderboard
  add column if not exists last_activity_at timestamptz;

alter table if exists public.leaderboard
  add column if not exists updated_at timestamptz not null default now();

drop trigger if exists set_leaderboard_updated_at on public.leaderboard;
create trigger set_leaderboard_updated_at
before update on public.leaderboard
for each row execute function public.touch_updated_at();

-- Points calculator — apply achievement deltas to a (employee, game) row.
create or replace function public.leaderboard_apply(
  p_employee_id text,
  p_game text,
  p_delta jsonb
)
returns void
language plpgsql
as $$
declare
  v_game text := lower(coalesce(p_game, 'all'));
  v_tw  integer := coalesce((p_delta ->> 'tournament_wins')::int, 0);
  v_ts  integer := coalesce((p_delta ->> 'tournament_seconds')::int, 0);
  v_tt  integer := coalesce((p_delta ->> 'tournament_thirds')::int, 0);
  v_mw  integer := coalesce((p_delta ->> 'match_wins')::int, 0);
  v_ml  integer := coalesce((p_delta ->> 'match_losses')::int, 0);
  v_dr  integer := coalesce((p_delta ->> 'draws')::int, 0);
  v_pa  integer := coalesce((p_delta ->> 'participations')::int, 0);
  v_rv  integer := coalesce((p_delta ->> 'rule_violations')::int, 0);
  v_ns  integer := coalesce((p_delta ->> 'no_shows')::int, 0);
  v_points_delta integer :=
      v_tw * 20
    + v_ts * 15
    + v_tt * 10
    + v_mw * 5
    + v_pa * 2
    - v_rv * 5
    - v_ns * 3;
begin
  if p_employee_id is null or btrim(p_employee_id) = '' then
    return;
  end if;

  insert into public.leaderboard (
    employee_id, game, total_points,
    tournament_wins, tournament_seconds, tournament_thirds,
    match_wins, match_losses, draws,
    participations, rule_violations, no_shows,
    last_activity_at
  )
  values (
    upper(p_employee_id), v_game, v_points_delta,
    v_tw, v_ts, v_tt, v_mw, v_ml, v_dr, v_pa, v_rv, v_ns,
    case when v_points_delta <> 0 then now() else null end
  )
  on conflict (employee_id, game) do update
  set
    total_points       = public.leaderboard.total_points + v_points_delta,
    tournament_wins    = public.leaderboard.tournament_wins + v_tw,
    tournament_seconds = public.leaderboard.tournament_seconds + v_ts,
    tournament_thirds  = public.leaderboard.tournament_thirds + v_tt,
    match_wins         = public.leaderboard.match_wins + v_mw,
    match_losses       = public.leaderboard.match_losses + v_ml,
    draws              = public.leaderboard.draws + v_dr,
    participations     = public.leaderboard.participations + v_pa,
    rule_violations    = public.leaderboard.rule_violations + v_rv,
    no_shows           = public.leaderboard.no_shows + v_ns,
    last_activity_at   = case
                           when v_points_delta <> 0 then now()
                           else public.leaderboard.last_activity_at
                         end;
end;
$$;
