-- ============================================================
-- Migration 22: Multi-player team support for tournaments
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. Add players_per_team to tournaments
--    1 = Singles (1v1), 2 = Doubles (2v2), 3 = Triples (3v3)
alter table public.tournaments
  add column if not exists players_per_team integer not null default 1;

-- Backfill existing Carrom tournaments to 2 (doubles)
update public.tournaments
  set players_per_team = 2
  where lower(game) = 'carrom';

-- 2. Junction table: all players in each match slot
create table if not exists public.tournament_match_players (
  id          bigint generated by default as identity primary key,
  match_id    bigint not null
                references public.tournament_matches(id)
                on update cascade on delete cascade,
  employee_id text not null
                references public.employees(employee_code)
                on update cascade on delete cascade,
  team        text not null check (team in ('A', 'B')),
  position    integer not null default 1,  -- 1 = captain, 2, 3 …
  created_at  timestamptz not null default now(),
  unique (match_id, employee_id)
);

create index if not exists tmp_match_idx      on public.tournament_match_players (match_id);
create index if not exists tmp_employee_idx   on public.tournament_match_players (employee_id);

-- RLS: anyone can read; only authenticated users can insert/update (admin gate is in app layer)
alter table public.tournament_match_players enable row level security;

create policy "tournament_match_players_select"
  on public.tournament_match_players for select
  using (true);

create policy "tournament_match_players_insert"
  on public.tournament_match_players for insert
  with check (auth.role() = 'authenticated');

create policy "tournament_match_players_delete"
  on public.tournament_match_players for delete
  using (auth.role() = 'authenticated');